[workspace]
members = [
  "modules/cjdev",
  "modules/cli_cj",
  "modules/ddd_cj",
  "modules/my_derive",
  "modules/result_cj",
  "modules/toml_cj",
]
build-members = []
test-members = []
compile-option = "-Woff unused"
override-compile-option = ""
link-option = ""
target-dir = ""

[dependencies]
dslkit = { git = "https://gitcode.com/belyaev-mikhail/Cangjie-DSLKit" }
