[package]
cjc-version = "1.0.5"
name = "cjdev"
description = "nothing here"
version = "0.1.0"
target-dir = ""
output-type = "executable"
compile-option = ""
override-compile-option = "-Woff unused"
link-option = ""
package-configuration = {}

[dependencies]
