[package]
  cjc-version = "1.0.5"
  name = "my_derive"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
