"""Generate docs/adr/README.md from the ADR files themselves.

The index is derived data, never hand-edited: an ADR's number is its issue's
(ADR-0024), so the table is a function of the files in docs/adr/ and nothing
else. Run with --check to fail instead of writing when it is stale - the same
shape `ruff format --check` has, which is what tests/test_adr_index.py runs.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = ROOT / "docs" / "adr"
INDEX = ADR_DIR / "README.md"

# Line 1 names the decision. The Status line is the contract the table renders:
# `Status: accepted, YYYY-MM-DD. Closes #N.` then anything else, verbatim -
# the date and the Closes clause are consumed, the rest becomes the cell
# ("superseded by ADR-NNNN", and the like).
HEADING = re.compile(r"^# ADR-(\d{4}): (.+)$", re.MULTILINE)
STATUS = re.compile(
    r"^Status:[ \t]*(\w+)(?:,?[ \t]*\d{4}-\d{2}-\d{2})?[.; \t]*(.*)$",
    re.MULTILINE,
)

HEADER = """\
# ADR

One decision per file, ≤ 1 page: the decision and why, not how it was reached — a
benchmark's table goes in the PR, the ADR keeps the result. An accepted ADR is not
rewritten: a new one replaces it, saying "supersedes ADR-NNNN". In discussion `D7`
≡ `ADR-0007`.

An ADR's number is the number of the issue whose resolution is that decision
([ADR-0024](0024-adrs-numbered-by-issue.md)): allocated when the issue is created,
unique under parallel pull requests, sparse by design — an issue that resolves
without a real choice leaves no ADR.

This index is generated by `tools/adr_index.py`; a test fails when it is stale.
Never edit it by hand - run the script after adding an ADR.

Template:

```md
# ADR-NNNN: <decision>

Status: accepted, YYYY-MM-DD. Closes #NNNN.

## Context
## Decision
## Consequences
```
"""


def parse(path: Path) -> tuple[str, str, str]:
    """The ADR's number, title and table status, or the reason it is malformed."""
    text = path.read_text(encoding="utf-8")
    heading = HEADING.search(text)
    status = STATUS.search(text)
    if heading is None or status is None:
        raise ValueError(
            f"{path.name}: needs '# ADR-NNNN: <title>' and a 'Status:' line "
            "matching the template in the index header"
        )
    number, title = heading.group(1), heading.group(2).strip()
    if path.stem.split("-", 1)[0] != number:
        raise ValueError(f"{path.name}: file name does not start with ADR-{number}")
    word, rest = status.group(1), status.group(2).strip()
    rest = re.sub(r"^Closes #\d+\.[ \t]*", "", rest).rstrip(".").strip()
    cell = f"{word}; {rest}" if rest else word
    return number, title, cell


def render_index() -> str:
    """The index document: the header, then one table row per ADR, by number."""
    parsed = {path.stem.split("-", 1)[0]: path for path in ADR_DIR.glob("????-*.md")}
    rows = sorted(
        (number, *rest)
        for number, rest in ((n, parse(p)[1:]) for n, p in parsed.items())
    )
    table = [
        "| # | Decision | Status |",
        "| --- | --- | --- |",
    ]
    for number, title, cell in rows:
        table.append(f"| [{number}]({parsed[number].name}) | {title} | {cell} |")
    return HEADER + "\n" + "\n".join(table) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the index is stale",
    )
    args = parser.parse_args(argv)

    rendered = render_index()
    stale = not INDEX.exists() or INDEX.read_text(encoding="utf-8") != rendered
    if args.check:
        if stale:
            print(
                "docs/adr/README.md is stale. Run: python tools/adr_index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    INDEX.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
